Updated Highcharts License.
splunk/splunk-sdk-javascript pull request #119
Opened 2021-06-14 07:59 UTC by rmaheshwari-splunk

Added LICENSE-HIGHCHARTS.txt and updated README.md regarding the same.

2021-06-15 17:58 UTC, fantavlik requested changes
We've been asked to pause on this update until Legal has had a chance to review. Let's move this to WIP state for now and remove the ticket from our Sprints

2021-06-16 09:19 UTC, rmaheshwari-splunk commented
> We've been asked to pause on this update until Legal has had a chance to review. Let's move this to WIP state for now and remove the ticket from our Sprints

Duly noted, we'll do the needful.

2021-09-23 16:13 UTC, fantavlik approved these changes

2021-09-23 17:12 UTC, ncanumalla-splunk commented
This looks good ! 👍

2021-09-24 05:24 UTC, merged